trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: Npm@1
  inputs:
    command: 'install'

- script: |
    yarn test:ci
    yarn build
  displayName: Build React front-end

# Publish Test Results
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/test/*.xml'
    failTaskOnFailedTests: true

# Publish Code Coverage Results
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: 'coverage/cobertura-coverage.xml'
    reportDirectory: 'coverage'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'build'
    ArtifactName: 'counter'

- script: |
    mkdir $(Build.ArtifactStagingDirectory)/end2endtests
    cp package.json $(Build.ArtifactStagingDirectory)/end2endtests
    cp -r end2end $(Build.ArtifactStagingDirectory)/end2endtests
  displayName: Copy end2end tests to staging ArtifactName

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)/end2endtests
    ArtifactName: 'end2end'
